In [1]:
from data import *

# data augmentation 

In deep learning tasks, a lot of data is need to train DNN model, when the dataset is not big enough, data augmentation should be applied.

keras.preprocessing.image.ImageDataGenerator is a data generator, which can feed the DNN with data like : (data,label), it can also do data augmentation at the same time.

It is very convenient for us to use keras.preprocessing.image.ImageDataGenerator to do data augmentation by implement image rotation, shift, rescale and so on... see [keras documentation](https://keras.io/preprocessing/image/) for detail.

For image segmentation tasks, the image and mask must be transformed **together!!**

## define your data generator

If you want to visualize your data augmentation result, set save_to_dir = your path

In [2]:
#if you don't want to do data augmentation, set data_gen_args as an empty dict.
#data_gen_args = dict()

data_gen_args = dict(rotation_range=0.2,
                    width_shift_range=0.05,
                    height_shift_range=0.05,
                    shear_range=0.05,
                    zoom_range=0.05,
                    horizontal_flip=True,
                    fill_mode='nearest')
myGenerator = trainGenerator(20,'data/membrane/train','image','label',data_gen_args,save_to_dir = "data/membrane/train/aug")

## visualize your data augmentation result

In [3]:
#you will see 60 transformed images and their masks in data/membrane/train/aug
num_batch = 3
for i,batch in enumerate(myGenerator):
    if(i >= num_batch):
        break

Found 30 images belonging to 1 classes.
Found 30 images belonging to 1 classes.


## create .npy data

If your computer has enough memory, you can create npy files containing all your images and masks, and feed your DNN with them.

In [4]:
image_arr,mask_arr = geneTrainNpy("data/membrane/train/aug/","data/membrane/train/aug/")
#np.save("data/image_arr.npy",image_arr)
#np.save("data/mask_arr.npy",mask_arr)

(120, 256, 256, 1) [[[[0.46666667]
   [0.5372549 ]
   [0.56862745]
   ...
   [0.58039216]
   [0.60392157]
   [0.60392157]]

  [[0.49019608]
   [0.69803922]
   [0.51764706]
   ...
   [0.52941176]
   [0.61568627]
   [0.62352941]]

  [[0.38039216]
   [0.6       ]
   [0.50588235]
   ...
   [0.59215686]
   [0.71764706]
   [0.80784314]]

  ...

  [[0.72156863]
   [0.63921569]
   [0.57647059]
   ...
   [0.58039216]
   [0.45098039]
   [0.46666667]]

  [[0.58823529]
   [0.65098039]
   [0.51764706]
   ...
   [0.8       ]
   [0.54901961]
   [0.4745098 ]]

  [[0.55686275]
   [0.68627451]
   [0.56862745]
   ...
   [0.88235294]
   [0.7254902 ]
   [0.67843137]]]


 [[[0.61176471]
   [0.61176471]
   [0.61176471]
   ...
   [0.34117647]
   [0.34117647]
   [0.50196078]]

  [[0.61176471]
   [0.61176471]
   [0.61176471]
   ...
   [0.34117647]
   [0.34117647]
   [0.50196078]]

  [[0.63137255]
   [0.63137255]
   [0.63137255]
   ...
   [0.37254902]
   [0.39607843]
   [0.4627451 ]]

  ...

  [[0.81176471]
   [